#!/usr/bin/env bash
#
# Build hass-datapoints-cards.js by concatenating all source files into a single
# IIFE that Home Assistant serves as the frontend resource.
#
# Usage:  bash scripts/build.sh   (from repo root)
#         bash build.sh           (from scripts/)
# Output: custom_components/hass_datapoints/hass-datapoints-cards.js

set -euo pipefail

# scripts/ lives one level below the repo root
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SRC_DIR="$REPO_ROOT/custom_components/hass_datapoints/src"
OUT_FILE="$REPO_ROOT/custom_components/hass_datapoints/hass-datapoints-cards.js"
MANIFEST="$REPO_ROOT/custom_components/hass_datapoints/manifest.json"

# Version: use BUILD_VERSION env var if set, otherwise read from manifest.json
VERSION="${BUILD_VERSION:-$(python3 -c "import json; print(json.load(open('$MANIFEST'))['version'])")}"

# Source files in dependency order
FILES=(
  "$SRC_DIR/constants.js"
  "$SRC_DIR/helpers.js"
  "$SRC_DIR/entity-name.js"
  "$SRC_DIR/chart-renderer.js"
  "$SRC_DIR/chart-utils.js"
  "$SRC_DIR/card-action.js"
  "$SRC_DIR/card-quick.js"
  "$SRC_DIR/card-chart-base.js"
  "$SRC_DIR/card-history.js"
  "$SRC_DIR/card-statistics.js"
  "$SRC_DIR/card-sensor.js"
  "$SRC_DIR/card-list.js"
  "$SRC_DIR/panel-history.js"
  "$SRC_DIR/card-editors.js"
  "$SRC_DIR/register.js"
)

{
  cat <<HEADER
/**
 * Hass Records – Lovelace Cards  v${VERSION}
 *
 * Cards:
 *   hass-datapoints-action-card      – Full form to record a custom event
 *   hass-datapoints-quick-card       – Simple one-field quick record card
 *   hass-datapoints-history-card     – History chart with event annotation markers
 *   hass-datapoints-statistics-card  – Statistics chart with event annotation markers
 *   hass-datapoints-sensor-card      – Sensor card with inline annotation icons
 *   hass-datapoints-list-card        – Browse, search, edit and delete all events (datagrid)
 *
 * Visual editors for all cards are included via card-editors.js.
 *
 * Built from src/ — do not edit this file directly. Run bash scripts/build.sh instead.
 */
(function () {
  "use strict";

HEADER

  for f in "${FILES[@]}"; do
    echo ""
    # Indent every line by 2 spaces so it sits inside the IIFE
    sed 's/^/  /' "$f"
    echo ""
  done

  cat <<'FOOTER'
})();
FOOTER
} > "$OUT_FILE"

# Stamp version into the console.info banner inside the built file
sed -i.bak "s/v0\\.3\\.0/v${VERSION}/g" "$OUT_FILE" && rm -f "$OUT_FILE.bak"

echo "✓ Built $OUT_FILE v${VERSION} ($(wc -l < "$OUT_FILE") lines)"
