/**
 * Cross-language consistency tests for trend algorithms.
 *
 * Verifies the TypeScript implementations produce numerically identical results
 * to the Python equivalents in anomaly_detection.py (the backend that runs in
 * Home Assistant).
 *
 * Algorithms covered:
 *   linear_trend | rolling_average | ema | polynomial_trend | lowess
 *   rate_of_change
 *
 * Dataset: 200 synthetic hourly points (~8 days) with a daily sinusoidal
 * cycle, gentle upward drift, irregular variation, and three outlier spikes.
 * Deterministic — loaded from fixtures/trend-dataset.json.
 */

import { describe, expect, it } from "vitest";
import { spawnSync } from "node:child_process";
import { join } from "node:path";
import DATASET_JSON from "./fixtures/trend-dataset.json";
import EXPECTED_JSON from "./fixtures/trend-expected.json";

import {
  buildEmaTrend,
  buildLinearTrend,
  buildLowessTrend,
  buildPolynomialTrend,
  buildRateOfChangePoints,
  buildRollingAverageTrend,
  getEmaAlpha,
  getLowessBandwidth,
  getTrendWindowMs,
} from "@/cards/history/analysis";

// ── Synthetic dataset ─────────────────────────────────────────────────────────
// 200 synthetic hourly sensor readings starting 2026-01-01T00:00:00.000Z.
// Formula: 20 + 5·sin(2π·i/24) + 0.015·i + 0.9·sin(i·7.3)
//   daily temperature cycle + gentle upward drift + irregular variation
// Spikes: i=20 (+12), i=83 (−9), i=151 (+10)
// Source: fixtures/trend-dataset.json (generated by scripts/gen-trend-fixture.py)

type Pt = [number, number];

const DATASET = DATASET_JSON as Pt[];
const EXPECTED = EXPECTED_JSON as unknown as Record<string, Pt[]>;

// expectPointsMatch makes 1 length assertion + 2 per output point (time + value).
const N = DATASET.length; // 200
const matchAssertions = (outputPoints: number) => 1 + outputPoints * 2;

// ── Python subprocess helper ──────────────────────────────────────────────────

const PYTHON =
  process.env.PYTHON_BIN ?? join(process.cwd(), ".venv/bin/python3");
const SCRIPT = join(process.cwd(), "scripts/trend_consistency.py");

function runPython(pts: Pt[], method: string, window = "24h"): Pt[] {
  const result = spawnSync(PYTHON, [SCRIPT], {
    input: JSON.stringify({ pts, method, window }),
    encoding: "utf-8",
    cwd: process.cwd(),
  });
  if (result.status !== 0 || result.error) {
    throw new Error(`Python script failed:\n${result.stderr}\n${result.error}`);
  }
  return (JSON.parse(result.stdout) as { pts: Pt[] }).pts;
}

// ── Comparison helper ─────────────────────────────────────────────────────────

/**
 * Assert two point series match within an absolute tolerance.
 * Used for cross-language comparison where tiny float differences are expected.
 */
function expectPointsMatch(
  ts: Pt[],
  py: Pt[],
  label: string,
  tol = 1e-9
): void {
  expect(ts.length, `${label}: length`).toBe(py.length);
  for (let i = 0; i < ts.length; i++) {
    expect(ts[i][0], `${label}: time[${i}]`).toBe(py[i][0]);
    const diff = Math.abs(ts[i][1] - py[i][1]);
    expect(diff, `${label}: |value[${i}]| diff = ${diff}`).toBeLessThanOrEqual(
      tol
    );
  }
}

// ── TS vs Python ──────────────────────────────────────────────────────────────

describe("cross-language consistency: TS worker vs Python", () => {
  describe("GIVEN linear_trend", () => {
    describe("WHEN computed over the synthetic dataset", () => {
      it("THEN worker and Python produce matching endpoints", () => {
        expect.assertions(matchAssertions(2));
        const ts = buildLinearTrend(DATASET);
        const py = runPython(DATASET, "linear_trend");
        expectPointsMatch(ts, py, "linear_trend");
      });
    });
  });

  describe("GIVEN rolling_average", () => {
    describe("WHEN window is 1h", () => {
      it("THEN worker and Python match", () => {
        expect.assertions(matchAssertions(N));
        const ts = buildRollingAverageTrend(DATASET, getTrendWindowMs("1h"));
        const py = runPython(DATASET, "rolling_average", "1h");
        expectPointsMatch(ts, py, "rolling_average/1h");
      });
    });

    describe("WHEN window is 6h", () => {
      it("THEN worker and Python match", () => {
        expect.assertions(matchAssertions(N));
        const ts = buildRollingAverageTrend(DATASET, getTrendWindowMs("6h"));
        const py = runPython(DATASET, "rolling_average", "6h");
        expectPointsMatch(ts, py, "rolling_average/6h");
      });
    });

    describe("WHEN window is 24h", () => {
      it("THEN worker and Python match", () => {
        expect.assertions(matchAssertions(N));
        const ts = buildRollingAverageTrend(DATASET, getTrendWindowMs("24h"));
        const py = runPython(DATASET, "rolling_average", "24h");
        expectPointsMatch(ts, py, "rolling_average/24h");
      });
    });
  });

  describe("GIVEN ema", () => {
    describe("WHEN window is 1h", () => {
      it("THEN worker and Python match", () => {
        expect.assertions(matchAssertions(N));
        const ts = buildEmaTrend(DATASET, getEmaAlpha("1h"));
        const py = runPython(DATASET, "ema", "1h");
        expectPointsMatch(ts, py, "ema/1h");
      });
    });

    describe("WHEN window is 6h", () => {
      it("THEN worker and Python match", () => {
        expect.assertions(matchAssertions(N));
        const ts = buildEmaTrend(DATASET, getEmaAlpha("6h"));
        const py = runPython(DATASET, "ema", "6h");
        expectPointsMatch(ts, py, "ema/6h");
      });
    });

    describe("WHEN window is 24h", () => {
      it("THEN worker and Python match", () => {
        expect.assertions(matchAssertions(N));
        const ts = buildEmaTrend(DATASET, getEmaAlpha("24h"));
        const py = runPython(DATASET, "ema", "24h");
        expectPointsMatch(ts, py, "ema/24h");
      });
    });
  });

  describe("GIVEN polynomial_trend", () => {
    describe("WHEN computed over the synthetic dataset", () => {
      it("THEN worker and Python produce a matching curve", () => {
        expect.assertions(matchAssertions(N));
        const ts = buildPolynomialTrend(DATASET);
        const py = runPython(DATASET, "polynomial_trend");
        expectPointsMatch(ts, py, "polynomial_trend", 1e-6);
      });
    });
  });

  describe("GIVEN lowess", () => {
    describe("WHEN window is 1h", () => {
      it("THEN worker and Python match", () => {
        expect.assertions(matchAssertions(N));
        const ts = buildLowessTrend(DATASET, getLowessBandwidth("1h", DATASET));
        const py = runPython(DATASET, "lowess", "1h");
        expectPointsMatch(ts, py, "lowess/1h", 1e-4);
      });
    });

    describe("WHEN window is 24h", () => {
      it("THEN worker and Python match", () => {
        expect.assertions(matchAssertions(N));
        const ts = buildLowessTrend(
          DATASET,
          getLowessBandwidth("24h", DATASET)
        );
        const py = runPython(DATASET, "lowess", "24h");
        expectPointsMatch(ts, py, "lowess/24h", 1e-4);
      });
    });
  });

  describe("GIVEN rate_of_change", () => {
    describe("WHEN window is 1h", () => {
      it("THEN worker and Python match", () => {
        expect.assertions(matchAssertions(N - 1));
        const ts = buildRateOfChangePoints(DATASET, "1h");
        const py = runPython(DATASET, "rate_of_change", "1h");
        expectPointsMatch(ts, py, "rate_of_change/1h");
      });
    });

    describe("WHEN window is 6h", () => {
      it("THEN worker and Python match", () => {
        expect.assertions(matchAssertions(N - 1));
        const ts = buildRateOfChangePoints(DATASET, "6h");
        const py = runPython(DATASET, "rate_of_change", "6h");
        expectPointsMatch(ts, py, "rate_of_change/6h");
      });
    });
  });
});

// ── Golden master: static regression tests ───────────────────────────────────
// Both TypeScript and Python are tested independently against the same fixed
// baseline stored in fixtures/trend-expected.json.  If either implementation
// changes its output, these tests will fail even if the two still agree with
// each other.  Regenerate the fixture with: python3 scripts/gen-trend-expected.py

describe("golden master: static regression tests", () => {
  describe("GIVEN linear_trend", () => {
    describe("WHEN TypeScript computes the result", () => {
      it("THEN it matches the golden expected output", () => {
        expect.assertions(matchAssertions(2));
        expectPointsMatch(
          buildLinearTrend(DATASET),
          EXPECTED.linear_trend,
          "golden/ts/linear_trend"
        );
      });
    });

    describe("WHEN Python computes the result", () => {
      it("THEN it matches the golden expected output", () => {
        expect.assertions(matchAssertions(2));
        expectPointsMatch(
          runPython(DATASET, "linear_trend"),
          EXPECTED.linear_trend,
          "golden/py/linear_trend"
        );
      });
    });
  });

  describe("GIVEN rolling_average", () => {
    describe("WHEN window is 1h", () => {
      it("THEN TypeScript matches the golden expected output", () => {
        expect.assertions(matchAssertions(N));
        expectPointsMatch(
          buildRollingAverageTrend(DATASET, getTrendWindowMs("1h")),
          EXPECTED["rolling_average/1h"],
          "golden/ts/rolling_average/1h"
        );
      });

      it("THEN Python matches the golden expected output", () => {
        expect.assertions(matchAssertions(N));
        expectPointsMatch(
          runPython(DATASET, "rolling_average", "1h"),
          EXPECTED["rolling_average/1h"],
          "golden/py/rolling_average/1h"
        );
      });
    });

    describe("WHEN window is 6h", () => {
      it("THEN TypeScript matches the golden expected output", () => {
        expect.assertions(matchAssertions(N));
        expectPointsMatch(
          buildRollingAverageTrend(DATASET, getTrendWindowMs("6h")),
          EXPECTED["rolling_average/6h"],
          "golden/ts/rolling_average/6h"
        );
      });

      it("THEN Python matches the golden expected output", () => {
        expect.assertions(matchAssertions(N));
        expectPointsMatch(
          runPython(DATASET, "rolling_average", "6h"),
          EXPECTED["rolling_average/6h"],
          "golden/py/rolling_average/6h"
        );
      });
    });

    describe("WHEN window is 24h", () => {
      it("THEN TypeScript matches the golden expected output", () => {
        expect.assertions(matchAssertions(N));
        expectPointsMatch(
          buildRollingAverageTrend(DATASET, getTrendWindowMs("24h")),
          EXPECTED["rolling_average/24h"],
          "golden/ts/rolling_average/24h"
        );
      });

      it("THEN Python matches the golden expected output", () => {
        expect.assertions(matchAssertions(N));
        expectPointsMatch(
          runPython(DATASET, "rolling_average", "24h"),
          EXPECTED["rolling_average/24h"],
          "golden/py/rolling_average/24h"
        );
      });
    });
  });

  describe("GIVEN ema", () => {
    describe("WHEN window is 1h", () => {
      it("THEN TypeScript matches the golden expected output", () => {
        expect.assertions(matchAssertions(N));
        expectPointsMatch(
          buildEmaTrend(DATASET, getEmaAlpha("1h")),
          EXPECTED["ema/1h"],
          "golden/ts/ema/1h"
        );
      });

      it("THEN Python matches the golden expected output", () => {
        expect.assertions(matchAssertions(N));
        expectPointsMatch(
          runPython(DATASET, "ema", "1h"),
          EXPECTED["ema/1h"],
          "golden/py/ema/1h"
        );
      });
    });

    describe("WHEN window is 6h", () => {
      it("THEN TypeScript matches the golden expected output", () => {
        expect.assertions(matchAssertions(N));
        expectPointsMatch(
          buildEmaTrend(DATASET, getEmaAlpha("6h")),
          EXPECTED["ema/6h"],
          "golden/ts/ema/6h"
        );
      });

      it("THEN Python matches the golden expected output", () => {
        expect.assertions(matchAssertions(N));
        expectPointsMatch(
          runPython(DATASET, "ema", "6h"),
          EXPECTED["ema/6h"],
          "golden/py/ema/6h"
        );
      });
    });

    describe("WHEN window is 24h", () => {
      it("THEN TypeScript matches the golden expected output", () => {
        expect.assertions(matchAssertions(N));
        expectPointsMatch(
          buildEmaTrend(DATASET, getEmaAlpha("24h")),
          EXPECTED["ema/24h"],
          "golden/ts/ema/24h"
        );
      });

      it("THEN Python matches the golden expected output", () => {
        expect.assertions(matchAssertions(N));
        expectPointsMatch(
          runPython(DATASET, "ema", "24h"),
          EXPECTED["ema/24h"],
          "golden/py/ema/24h"
        );
      });
    });
  });

  describe("GIVEN polynomial_trend", () => {
    describe("WHEN TypeScript computes the result", () => {
      it("THEN it matches the golden expected output", () => {
        expect.assertions(matchAssertions(N));
        expectPointsMatch(
          buildPolynomialTrend(DATASET),
          EXPECTED.polynomial_trend,
          "golden/ts/polynomial_trend",
          1e-6
        );
      });
    });

    describe("WHEN Python computes the result", () => {
      it("THEN it matches the golden expected output", () => {
        expect.assertions(matchAssertions(N));
        expectPointsMatch(
          runPython(DATASET, "polynomial_trend"),
          EXPECTED.polynomial_trend,
          "golden/py/polynomial_trend",
          1e-6
        );
      });
    });
  });

  describe("GIVEN lowess", () => {
    describe("WHEN window is 1h", () => {
      it("THEN TypeScript matches the golden expected output", () => {
        expect.assertions(matchAssertions(N));
        expectPointsMatch(
          buildLowessTrend(DATASET, getLowessBandwidth("1h", DATASET)),
          EXPECTED["lowess/1h"],
          "golden/ts/lowess/1h",
          1e-4
        );
      });

      it("THEN Python matches the golden expected output", () => {
        expect.assertions(matchAssertions(N));
        expectPointsMatch(
          runPython(DATASET, "lowess", "1h"),
          EXPECTED["lowess/1h"],
          "golden/py/lowess/1h",
          1e-4
        );
      });
    });

    describe("WHEN window is 24h", () => {
      it("THEN TypeScript matches the golden expected output", () => {
        expect.assertions(matchAssertions(N));
        expectPointsMatch(
          buildLowessTrend(DATASET, getLowessBandwidth("24h", DATASET)),
          EXPECTED["lowess/24h"],
          "golden/ts/lowess/24h",
          1e-4
        );
      });

      it("THEN Python matches the golden expected output", () => {
        expect.assertions(matchAssertions(N));
        expectPointsMatch(
          runPython(DATASET, "lowess", "24h"),
          EXPECTED["lowess/24h"],
          "golden/py/lowess/24h",
          1e-4
        );
      });
    });
  });

  describe("GIVEN rate_of_change", () => {
    describe("WHEN window is 1h", () => {
      it("THEN TypeScript matches the golden expected output", () => {
        expect.assertions(matchAssertions(N - 1));
        expectPointsMatch(
          buildRateOfChangePoints(DATASET, "1h"),
          EXPECTED["rate_of_change/1h"],
          "golden/ts/rate_of_change/1h"
        );
      });

      it("THEN Python matches the golden expected output", () => {
        expect.assertions(matchAssertions(N - 1));
        expectPointsMatch(
          runPython(DATASET, "rate_of_change", "1h"),
          EXPECTED["rate_of_change/1h"],
          "golden/py/rate_of_change/1h"
        );
      });
    });

    describe("WHEN window is 6h", () => {
      it("THEN TypeScript matches the golden expected output", () => {
        expect.assertions(matchAssertions(N - 1));
        expectPointsMatch(
          buildRateOfChangePoints(DATASET, "6h"),
          EXPECTED["rate_of_change/6h"],
          "golden/ts/rate_of_change/6h"
        );
      });

      it("THEN Python matches the golden expected output", () => {
        expect.assertions(matchAssertions(N - 1));
        expectPointsMatch(
          runPython(DATASET, "rate_of_change", "6h"),
          EXPECTED["rate_of_change/6h"],
          "golden/py/rate_of_change/6h"
        );
      });
    });
  });
});
