name: Commit Lint

on:
  pull_request:
    branches: [main]
    types: [opened, edited, reopened, synchronize]

jobs:
  commitlint:
    name: Validate commit messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .github/commitlint.config.js
          failOnWarnings: false
          helpURL: https://www.conventionalcommits.org/en/v1.0.0/
